# Generated by Django 4.2.1 on 2023-05-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_task_code_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(default="two-sum", unique=True),
            preserve_default=False,
        ),
    ]
