# Generated by Django 4.2.1 on 2023-05-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_task_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="topics",
            field=models.ManyToManyField(related_name="tasks", to="core.topic"),
        ),
        migrations.AlterField(
            model_name="taskreaction",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="core.task",
            ),
        ),
        migrations.AlterField(
            model_name="tasksubmission",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="core.task",
            ),
        ),
    ]
