# Generated by Django 4.2.1 on 2023-05-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_task_description_alter_task_solution"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input", models.TextField()),
                ("output", models.TextField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
