# Generated by Django 4.2.1 on 2023-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_tasksubmission_result_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
